default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  host: localhost
  username: postgres
  password:
  database: EuroVintVoting_development

test: &test
  <<: *default
  host: localhost
  username: postgres
  password:
  database: EuroVintVoting_test

production:
  url: <%= ENV['DATABASE_URL'] %>
cucumber:
  <<: *test
